apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: knative-serving
spec: {}
status: {}
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  {}
