apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: knative-eventing
spec: {}
status: {}
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  {}
