apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: eventinghello-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: eventinghello-ch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello
